### ISSUE TITLE
Why did you chose to not allow backspace to fire the mask?

### ISSUE THREAD

**Issue by vsalbuq** [BankFacil/vanilla-masker#31]
This question is just out of curiosity (I've deleted "8" from `BY_PASS_KEYS` array to keep the pattern when backspace is pressed).

**Comment by vdmrox** [comment]
Sorry for  bringing it up again, but maybe it could be optional. Sometimes we need the field to be empty, depending on validation rules. For example, I have a form which must receive a decimal different from 0.00. Otherwise I cannot send it to my back end. But whenever I try to delete the value, it comes up wit 0.00 again.
